version: '2'
services: 
  tomcat: 
    image: kaichun/gdctomcat
    container_name: tomcat_localhost
    ports: 
      - "8083:8080"
  nexus: 
    image: kaichun/gdcnexus
    container_name: nexus_localhost
    ports: 
      - "8081:8081" 
  svn: 
    image: kaichun/gdcsvn
    container_name: svn_localhost
    ports: 
      - "80:80"
  jenkins: 
    image: kaichun/gdcjenkins
    container_name: jenkins_localhost
    ports: 
      - "8080:8080"